apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:OfctoAgyewB4pHoV3t5uSCrBKgaG80Yvri5LeH6wpM1LFHajPJpSq4Xxi6ZMZ9zuelcJHiQmRslOuds8dhAQjccDoTRkcNDy,iv:gn/iMARWeTJayT2pGoWK9jKCtKILpTVxkbV09eI6p5M=,tag:onyIG3cO3H80AZFqbSDKyA==,type:str]
kind: Secret
metadata:
    name: cloudflare-holovko-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcjRrZjRaV2kwWEhCLzF2
            djYxZ0tYajlxM0JhKzdkM0lMSkVSaVBsWXcwCm5BbXhTRG90QUpkUEkrcmg5SlhR
            WFpjZVZhUG1vMmQ2V1dnTkpuRWZXWnMKLS0tIGZHZXFXazUrYWhWL2lJNHV3aU96
            RWNpaVVtaGxQOGEyNU1qK0dQSTF3d2sK244gDpkT3AZlkKIr2E2FfQx8X+ZBAu0p
            P9QzGEmpfb9DmDDyNkg0+X3Jeim7IHKCC9SyJRIKwZvkSdcqnWut/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T09:05:02Z"
    mac: ENC[AES256_GCM,data:BdXyzT6/0230PDZbdEJzXQmnKBZnKUyNGJZ0NGjse4LAwJ749E331g7MZjQnS1OdFg+zAA8U4OvY6UBPfAM+H9pMQuvQzDJFk7nSefwpBrfaZeZ20q+tSeqc2pdV4mzpwckZbv0SAu59Mvlo+9BFHT/izhB5/Dx+iSHi0EhFDEI=,iv:voIzWqWZDm6dqiPnMI3rN9bhTM6oT3/B2TkCDqCTL28=,tag:TT4zDFebpV4fkjtNULlc9g==,type:str]
    version: 3.13.1
