apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:gxtnVojaV6SfPeiuEp7O3svRRy1YcpAsoHCWmp+E6swn+X9PfHXJhVpAgvAAnNSAYKXE6sZ+K1UonpeY4LQPund0kITlOqy+ddG/Ssgql5BRUvL1L52GX+WnC0xynfX30GhTCZzg3RHC/G+BTXUAkEpqfleyLdzb92BhWrkGCVzYhQHbilXtKdOdk8vacuhgVb3LZfugeyL4qmmUy7Rg2JtkY4wnW0OiwhW4Mv2wc/W4gSFKFNN+UnwTQcVEFkScvWWriqPyKAYZiz6ImS1OT0S2PpLXPL3/R1FJg3YLbRG1wx/zH9y14Cw/bRY=,iv:2WN6VOwdulDxjNKi8nIe1/X/CbacsJ6slzG2iGoafaY=,tag:OvOiWX8jazsMsDljlalNOw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SEZxTjNiZVBqZWIxRFk4
            dldsM3hjWEdnWnNrZW1aeHoxMHFKODNuYUZNCmkyRUcyY3ZuQ1dsRDNFajFQSTFU
            TWlnMGsrSDFGM1V1M2t3aXhhWjVDdlEKLS0tIFZJM1hrcm9ZWmVnVVRmdnlsakFr
            QmxIZFZzaFdUTDU4RG1JcWtSN25lbVUKfOGPqTiN88UesOzovcX+YDJf0Rj5Xe2Q
            IUBZdTAEjDbxQbQajCoI1OBLVH5yqgSBkf0Dc4pATIGVxGGiGNZz0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T14:31:02Z"
    mac: ENC[AES256_GCM,data:0x1CwfSxKskvXntjqLSYqcYGQ+RFyUyjdOWL86A9oM3zqbHSdTiZxSqfoUIBFUQwbgu76uj3ltdffXz2Q5ci4RZ0hXKKsgr/OM6HWsU78q3uKfL21q3VcWKo3DtpWASrBBjjAVJXuup8WwbxGA1Q9Z90cyYubW8rfVrzd/QOpec=,iv:HQ5VF/sNP4NIdv0lcG4KMo/WOVOsDSEzDyluAr2veNA=,tag:EFzZTOqGnrVvHoVNGfG6hA==,type:str]
    version: 3.13.1
