apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZzgQoz094eI=,iv:uTKYU4rFlIwkEHLV6X9F0AZYtIOKrKesCyEZl1Y2z3A=,tag:fGDOzcsXFV1Ob/b8QCRezg==,type:str]
    user: ENC[AES256_GCM,data:WIPvNRO6mz8=,iv:2Pko+iRdAWsbgxeh+H3nTp8/9KfkbYw2/Dt7yb3GDgM=,tag:CVd+b8fX9uTALLAYbFdaJw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT0U0VUFBWWY1TTJrU2ll
            SUJlRjhZZ1hMaVV3STVHVlVYZjBPcnBsYmw0CjBzYTd6Y0M5RVJsM3pGYzJwYTRw
            YkIwbUs0M2hwaVd1VThrQU5GSkRjMHMKLS0tIFlEeGM2Yk92OGFNTlJUZWhzQ3E1
            ZUoyeUQxa2lFQjVtRzBndll4dU83VDQKk1xfQjNd2wvz4qlbVLQLJGVSrB/cPvOd
            P/4n/sDuLL7q/o89hdZsioxfPfx5R/Ir3hKZYYuiFnItfhqu0BQ+hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T17:20:36Z"
    mac: ENC[AES256_GCM,data:EBGRdSOQcaeAKW4R0GItzM6VPcbatiVrKxvba5FKspebKK5W8457IebeSaUgEn1jEb3wZPyRCiSlfYpXx4Pnhzv99ribXj2MklnNjMbUn5SZRLZ0II8+ZRYwsmmir9LfU+k/2W7RVqTAwWgUklRKL1MAJfNTSX3gxuNjH2sMqTI=,iv:ejAmP2jwblhABd5/lirQDTSnrqVeNRofuXBGkcUvtzo=,tag:70uLOrI7JgTksy1CWWDlRA==,type:str]
    version: 3.13.1
