apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plants
spec:
  ingressClassName: traefik
  rules:
    - host: plants.holovko.org
      http:
        paths:
          - backend:
              service:
                name: hortusfox-web
                port:
                  number: 80
            path: /
            pathType: Prefix

