apiVersion: apps/v1
kind: Deployment
metadata:
  name: plants-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plants
  template:
    metadata:
      labels:
        app: plants
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
      containers:
        - name: hortusfox-web
          image: ghcr.io/danielbrendel/hortusfox-web:latest
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/www/html/public/img
              name: app-images
            - mountPath: /var/www/html/app/logs
              name: app-logs
            - mountPath: /var/www/html/public/backup
              name: app-backup
            - mountPath: /var/www/html/public/themes
              name: app-themes
            - mountPath: /var/www/html/app/migrations
              name: app-migrate
          envFrom:
            - configMapRef:
                name: hortusfox-web-cm
            - secretRef:
                name: hortusfox-web-secret
      volumes:
        - name: app-images
          persistentVolumeClaim:
            claimName: app-images-pvc
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs-pvc
        - name: app-backup
          persistentVolumeClaim:
            claimName: app-backup-pvc
        - name: app-themes
          persistentVolumeClaim:
            claimName: app-themes-pvc
        - name: app-migrate
          persistentVolumeClaim:
            claimName: app-migrate-pvc
