apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  serviceName: "mariadb"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mariadb
        image: mariadb
        envFrom:
          - secretRef:
              name: mariadb-secret
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: db_data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db_data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi
