apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:eo89jWJyFmYx3jUNTTT2jJ4n+pTxxGFYWUO0iNHQx1Nk1eOT,iv:ktnej04SUfnqg21Z8MsY5zIZlbqLGRFyLsfzuTLuk/A=,tag:GwHrz8ZmPoDs+qVJFuw13A==,type:str]
kind: Secret
metadata:
    name: grafana-admin-pass-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSGV0NGlWQUlmTGJqNkQv
            NW1zQ3k1Sk9aa1BHMkhGT1ErSCtFRm9zZ1EwCnJvOUZhd1lWcG5HMGplV2tHOGNW
            Y3NJUVBYcjYxbFJ6ZEpENWlweHhEUWMKLS0tIFRKVVd2TTk1c09LeTVGblRoOHFv
            L2VZZXAyVzcramluTkRLSU9aVnpHMjAK8ezwggFjW6LUqcC1STfjxrhHgZ8B1/Vp
            utvW2GZ4Fk6bVHLAVj5KPoFWcCMR7BGg7rV31uGf8ZCylLcb26sYGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T16:37:48Z"
    mac: ENC[AES256_GCM,data:LTv2K+AYhpAY3dKA/RGHUCcA0h0lMuf1aZYotJErokqR2Vwbjk3Uj4hRJOcEFKiR5+J46vEFEAaHbDygJES0KrbxUZ36+16F4KLoLtnlUzHv5d2fwzuexiZMK/wnDi1ZwMlJWmjCYgJBfRBIa6PdXZSlXzs4WOJUdIN6r6Mzmvc=,iv:ZrvMOu0hLPiSUwgdP/4kiwXhdbDaEN6bZjIlnjlRn10=,tag:BxVMe1xCD5bUXv3TqQLuKw==,type:str]
    version: 3.13.1
