apiVersion: v1
data:
    access_token: ENC[AES256_GCM,data:asnXE6eiNb/TTsUuN3D3j5dj57HpcEkP7238hBytf1WR2wsR,iv:LbGbmtH8608uMDQmbTr8LehAPogIGyaFekAuyDjMUmw=,tag:BpkPWfwI4A+ptJzYDJcxnA==,type:str]
    app_key: ENC[AES256_GCM,data:pXhLIRwtyFjtvHgfGZJwDzre1M3CwSKQik4xodnVPpvaxWND,iv:mSAX3VAz9mstVn0lxfiLjGrrruTbPEcNLCKpVjrZIxc=,tag:DeeLMW+6RFFVtHxOuLtWig==,type:str]
    db_password: ENC[AES256_GCM,data:zvPYLtlj/pw=,iv:qLipXrAREco8CYrmP2CXVcMIPTFgUYBGXj/enbaessA=,tag:xZz51CKYX5U6rLrcVksoog==,type:str]
    db_root_password: ENC[AES256_GCM,data:z+pi+8NhLf0yro1L2EfNZkbU9jPkMS4jRQzQGQ06RLzg4IH8,iv:zLfY+6Gw0S2UROwqNCZF4wuGs8BTgnLIcdVmGVvD+pc=,tag:u52Sl5pESIXmAO6jdKwgHg==,type:str]
    static_cron_token: ENC[AES256_GCM,data:CEWcJdStBT49ryuJ94blgQ/9kswi/yWhOheRVtSfR3sV4K5Q,iv:aH9VKiX+puv906Hm0ABlFmdfy3fa4tobCtkZgEtjADc=,tag:dh9GsR/YgXmiue9lAVAHrw==,type:str]
kind: Secret
metadata:
    name: firefly-iii-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaUpoMmpPNVNsTUpCWjdF
            dGQ1SVk3WTVKekVxVUNac1c1d0lJZjg0WDJBCmxNQnFzZGorbzNYM0hZcy92UlJs
            L1RUakl1cmxLc1pTRSthN3E3NUxUZjgKLS0tIGpKejEvSFhGVm9teDhiZEN5SjV3
            VnZad0xObGFlOEl3TzhJYXRNVjV0ak0KgvWTMuBhPAlJf1nG3SlOFFcNo6pJLkOQ
            kFgy7VmS0G10qf4nExD77wBbPeJGu20gQCL5n6fwvsjMYT7U9U7/fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T15:35:20Z"
    mac: ENC[AES256_GCM,data:nIhn3OdCBCTwnG5gJVz2WkSqP9bcvhavGl2oPHNzCTTedNyHfm1AQ/hvfciqmkFi3gm7D6+l1bmzVxQSIOJx+zxwkdozXo9qPcuVEO7cXBLUo5hQ1w3qhMRJKxE6wmlTtZy487imdOvljg8avGD9VQq0KB/G8UTQncQIbvOB1DA=,iv:oqKsydZElW5cHUNmt/j1benBqQB9Jqv8ttHBqkNWUf4=,tag:X/J04e+qOif3y0bEirgBmw==,type:str]
    version: 3.13.1
