apiVersion: v1
data:
    access_token: ENC[AES256_GCM,data:8LSrNy5XwzS1fNu41qDUVdOLaoCaic1NzBdoqnSyv2ATOI5x,iv:I8Fv3/zWKTH0Lbl1rBpTrCfx374lKWCY6YWIwbK2oVU=,tag:Zl6VnxGhxQMEL/8VaPgBhg==,type:str]
    app_key: ENC[AES256_GCM,data:+ljAw7b4cowP6psm2lS8pqz0ckg3qVxD5qzwGsbvkl6Hbl6Vgi+Y26UjF1qNjJAHOahj4w+WuznpIt19qEXfuK7qbe8=,iv:kfUX9cHNXwW0BVHFJoynwOCbr3F1qD0qFa/51ZdvRiA=,tag:iiCkLcSh44IT7CDCZHfj6w==,type:str]
    db_password: ENC[AES256_GCM,data:7upHd+QgWMU=,iv:nAN+PSJ20dsJOs8RpgStXtBgW7nE5Lq1xfJm0QS9xoQ=,tag:FpPEnRq1qzwr0gVVK0ZpXA==,type:str]
    db_root_password: ENC[AES256_GCM,data:obsi5zr8NvaqAaC48aWD54vAM/uwEY5AgIVwZ4PuZHwzPTyq,iv:OlgJqk3+4uB/FIZWz1t+QWNW0mbzZMKS7PrckH6XeLs=,tag:cv9NU2MuN0xFSHUBiNngbw==,type:str]
    static_cron_token: ENC[AES256_GCM,data:3wz9x7YjMiUsh1rHWmu5XlbFtX/nU7im0B+4yMDwFxqbDS985ZVMuBuZCf8=,iv:r7fVxkYMnQ4pQvLel/sLk5B3FTiWBRb0PJpVFPnGjV4=,tag:mHPJS1y+O5EOGf4RSjYl0g==,type:str]
kind: Secret
metadata:
    name: firefly-iii-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdVdwUEdJaHduUUVDRVA0
            ZnQreFoyMTlYd1FvM3JlcTBXbngrWXZQdENjCndPZVhMTVVyQkFDcWprd0hGY3hG
            cXJRNnJLT2Y2ckd6VVdOM3RsWm5LSmMKLS0tIFZHNG9ONGlueTJoWjIzRUdvRCtN
            R3VhMjJWNEJCeTRsTTB0dDdPeGJ2RG8Kn1uwCRQavvuF/GU0ACnPMMsinLEV+rzH
            vTJKO7DEspCOi8welkpBs8Tlf798PCtt6NFWWtkAOOI1n6ekJYKuzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4eua866s66qduq4zcpxd497crca979cqxmldlqt8suz2lmze9fqhwyt7q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T16:18:07Z"
    mac: ENC[AES256_GCM,data:rwniKPZHJGEiyLBlAr43MJ/iZa1Mmzy3MFXW7EBs630GW2E/3B2VFCcsHdJm5xKOxOW889TqYatiB0X+/PXNVCESoOr3tnkXt2BbL5Z1yeX4qMPA6zJ2STtpkuBv4UsQB0qV9YWw9UowMaSCcFTC5YvJWq5kxUjRoRi8Bwt1jRs=,iv:mDCiN1fGQ3OnjimyQLZ247puUvQr0ijj02GuSOWbFd0=,tag:5ylU4D4y0dwQdi1Mxtq9Jw==,type:str]
    version: 3.13.1
